version: '2'

services:
  drone-server:
    image: drone/drone
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=ac807d204e0b0067f050
      - DRONE_GITHUB_SECRET=6c137730c3fde0272d12a31388b282494d00b5b1
      - DRONE_SECRET=49294929

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=49294929
