version: '2'
services:
  hexo:
    container_name: hexo
    image: zuolan/hexo
    restart: always
    volumes:
      - /:/host_dir
      - $HEXO/:/mnt
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
  nginx:
    container_name: hexo_web
    image: nginx:alpine
    restart: always
    volumes:
      - $HEXO/public:/usr/share/nginx/html:ro
    ports:
      - "4000:80"
